# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
permalink: /:title/
title: Force Multiplication through IT Automation
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  “Force Multiplication through IT Automation” comes from the military, where
  a force multiplier is an attribute such as technology or experience that
  allows a small force to accomplish the same results of a force many times
  larger. In information technology, automation tools such as PowerShell allow
  an individual IT professional to be just as effective as a large staff
  performing tasks manually.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.hofferle.com" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/New_York
twitter_username: jhofferle
github_username:  jhofferle
linkedin_username: jhofferle
#highlighter: rouge

defaults:
  scope:
    path: "assets/img"
  values:
    image: true

# Build settings
markdown: kramdown
remote_theme: jekyll-book-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
